apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-b
  name: service-b-service
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: service-b
  type: NodePort
status:
  loadBalancer: {}