apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-b
  name: service-b-service
spec:
  ports:
  - port: 9003
    protocol: TCP
    targetPort: 9003
    nodePort: 30996
  selector:
    app: service-b
  type: NodePort
status:
  loadBalancer: {}