apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  serviceAccountName: tekton-triggers-sa
  serviceType: ClusterIP
  triggers:
    - name: github-trigger
      interceptors:
        - github:       
            secretRef:
              secretName: webhook-secret
              secretKey: token     
            eventTypes:
              - push
      bindings:
        - name: pipeline-binding
      template:
        name: pipeline-template