apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: spring-boot-k8s-build-and-deploy-pipeline
spec:  
  params:
    - name: pathToDockerFile            
      default: 
    - name: pathToAppGatewayContext
      default:
    - name: pathToServiceAContext
      default:
    - name: pathToAppGatewayDeployConfig
      default:
    - name: pathToAppGatewayServiceConfig
      default:
    - name: pathToServiceADeployConfig
      default:
    - name: pathToServiceAServiceConfig
      default:
  resources:
    - name: docker-source
      type: git
    - name: application-gateway-image
      type: image
    - name: service-a-image
      type: image
  tasks:
    - name: build-application-gateway
      taskRef:
        name: docker-build-and-deploy
      params:
        - name: pathToDockerFile
          value: "$(params.pathToDockerFile)"
        - name: pathToContext
          value: "$(params.pathToAppGatewayContext)"
      resources:
        inputs:
          - name: docker-source
            resource: docker-source
        outputs:
          - name: builtImage
            resource: application-gateway-image

    - name: build-service-a
      taskRef:
        name: docker-build-and-deploy
      params:
        - name: pathToDockerFile
          value: "$(params.pathToDockerFile)"
        - name: pathToContext
          value: "$(params.pathToServiceAContext)"
      resources:
        inputs:
          - name: docker-source
            resource: docker-source
        outputs:
          - name: builtImage
            resource: service-a-image

    - name: kube-deployment
      taskRef:
        name: kube-deployment
      runAfter:
        - build-application-gateway
        - build-service-a
      params:
        - name: pathToDeployConfig
          value: "$(params.pathToAppGatewayDeployConfig)"
        - name: pathToServiceConfig
          value: "$(params.pathToAppGatewayServiceConfig)"
      resources:
        inputs:
          - name: docker-source
            resource: docker-source