apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: app-gateway-docker-build-and-deploy-task-run
spec:
  serviceAccountName: spring-boot-service
  taskRef:
    name: app-gateway-docker-build-and-deploy
  params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToAppGatewayContext
      value: /workspace/docker-source/application-gateway/
    - name: pathToAppGatewayDeployConfig
      value: /workspace/docker-source/application-gateway/kubernetes/application-gateway-deploy.yaml
    - name: pathToAppGatewayServiceConfig
      value: /workspace/docker-source/application-gateway/kubernetes/application-gateway-service.yaml
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: application-gateway-git
    outputs:
      - name: builtImage
        resourceRef:
          name: application-gateway-image