apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: pathToDockerFile
    description: Docker File
    default: 
  - name: pathToAppGatewayContext
    description:
  - name: pathToAppGatewayDeployConfig
    description:
    default:
  - name: pathToAppGatewayServiceConfig
    description:
    default:
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: spring-boot-k8s-pipeline-run
    spec:
      serviceAccountName: spring-boot-service
      pipelineRef:
        name: spring-boot-k8s-build-and-deploy-pipeline
      resources:    
      - name: docker-source
        resourceRef:
          name: spring-boot-k8s-git
      - name: application-gateway-image
        resourceRef:
          name: application-gateway-image-resource
      - name: service-a-image
        resourceRef:
          name: service-a-image-resource
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToAppGatewayContext
          value: /workspace/docker-source/application-gateway/
        - name: pathToServiceAContext
          value: /workspace/docker-source/service-a/
        - name: pathToAppGatewayDeployConfig
          value: /workspace/docker-source/application-gateway/kubernetes/application-gateway-deploy.yaml
        - name: pathToAppGatewayServiceConfig
          value: /workspace/docker-source/application-gateway/kubernetes/application-gateway-service.yaml
        - name: pathToServiceADeployConfig
          value: /workspace/docker-source/service-a/kubernetes/application-gateway-deploy.yaml
        - name: pathToServiceAServiceConfig
          value: /workspace/docker-source/service-a/kubernetes/application-gateway-service.yaml