apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-a
  name: service-a-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 31708
  selector:
    app: service-a
  type: NodePort
status:
  loadBalancer: {}