apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: application-gateway-deploy
  name: application-gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-gateway-deploy
  strategy: 
    type: RollingUpdate 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: application-gateway-deploy
    spec:
      containers:
      - image: bashdocker/application-gateway:latest
        name: application-gateway
        imagePullPolicy: Always
        resources: {}
status: {}