apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: application-gateway-deploy
  name: application-gateway-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32308
  selector:
    app: application-gateway-deploy
  type: NodePort
status:
  loadBalancer: {}